### ISSUE TITLE
Connection fails, debug not working

### ISSUE THREAD

**Issue by tomaae** [Limych/ha-jq300#8] opened 2020-07-13 01:33 UTC
**Version of the custom_component**

Commit: efa23c8

**Describe the bug**
Integration stops working after a while. May be caused by number of requests, after failure, official app reports too many requests and stops updating for a bit.

If I enable debug, it wont even log in.

**Debug log**

```text
2020-07-13 03:29:59 ERROR (SyncWorker_7) [custom_components.jq300] Sorry.. Something went wrong...
2020-07-13 03:30:00 ERROR (SyncWorker_7) [custom_components.jq300] Sorry.. Something went wrong...
2020-07-13 03:31:00 ERROR (SyncWorker_9) [custom_components.jq300] Sorry.. Something went wrong...
2020-07-13 03:31:01 ERROR (SyncWorker_9) [custom_components.jq300] Sorry.. Something went wrong...
.....
```

If debug is enabled for integration:
```text
2020-07-13 03:23:02 ERROR (SyncWorker_4) [custom_components.jq300] Sorry.. Something went wrong...
2020-07-13 03:23:04 ERROR (SyncWorker_4) [custom_components.jq300] Sorry.. Something went wrong...
2020-07-13 03:23:08 WARNING (MainThread) [homeassistant.setup] Setup of jq300 is taking over 10 seconds.
2020-07-13 03:23:13 ERROR (MainThread) [custom_components.jq300] Timeout fetching to****s@gm**l.com device's sensors
2020-07-13 03:23:13 ERROR (MainThread) [homeassistant.setup] Setup failed for jq300: Integration failed to initialize.
```

**Additional context**
For start, debug mode needs to be fixed so we can get more info. Right now integration will fail on startup if debug is enabled
```text
logs:
    custom_components.jq300: debug
```

**Comment by insajd** [comment] 2020-07-13 13:13
Same issue here

**Comment by gabrielR0** [comment] 2020-07-15 07:02
Same here

**Comment by Limych** [comment] 2020-07-15 20:15
I'm sorry, I still can’t verify the reason.  My IP is blocked by the Chinese. Change it is not yet possible.

**Comment by Limych** [comment] 2020-07-15 20:17
> Same here, I believe we have some API call limit, in the mobile application I got a message that I'm trying to retrieve the data too fast

Try to update component to latest version and change your external IP. I hope, it's helps to you.

**Comment by Limych** [comment] 2020-07-15 21:51
I'm successfully change IP and successfully connect to cloud with latest component version:

```text
2020-07-16 00:47:00 INFO (MainThread) [custom_components.jq300] Version 0.7.9
2020-07-16 00:47:00 INFO (MainThread) [custom_components.jq300] If you have ANY issues with this, please report them here: https://github.com/Limych/ha-jq300/issues
2020-07-16 00:47:00 DEBUG (MainThread) [custom_components.jq300] Connecting to account ***@hu****s.com
2020-07-16 00:47:00 DEBUG (SyncWorker_10) [custom_components.jq300] Querying http://www.youpinyuntai.com:32086/ypyt-api/api/app/loginByEmail
2020-07-16 00:47:01 DEBUG (SyncWorker_10) [custom_components.jq300] _query ret 200
2020-07-16 00:47:01 DEBUG (SyncWorker_10) [custom_components.jq300] b'{"action":"loginByEmail","code":2000,"uid":31061285,"safeToken":"6F8ED710BE1F45C78526AE5257F91BF4","expireAt":0,"systime":0}'
2020-07-16 00:47:01 DEBUG (SyncWorker_10) [custom_components.jq300] Updating devices list for account ***@hu****s.com
2020-07-16 00:47:01 DEBUG (SyncWorker_10) [custom_components.jq300] Querying http://www.youpinyuntai.com:32086/ypyt-api/api/app/deviceManager
2020-07-16 00:47:01 DEBUG (SyncWorker_10) [custom_components.jq300] b'{"action":"deviceManager","code":2000,"deviceInfoBodyList":[{"circleid":"57bc22e972f9d27416581187","pt_name":"JQ-300","pt_model":"JQ_300","brandname":"\xe5\x93\x81\xe4\xbc\x98","logo":"mlLogo.png","onlinestat":1,"flag":1,"id":24184,"deviceid":15573,"devstatus":6,"deviceToken":"84E17B9117426E7BA417","status":1,"href":"/resource/page/hcho/indexPm25.html","pic":"20161026101634psgscf591477448194","weburl":"http://market.cmbchina.com/ccard/xyksq/xyksq.html?WT.srch=1&WT.mc_id=N3700BD1057Z074200BZ","updtime":"1477448195","repairstatus":null}]}'
2020-07-16 00:47:02 DEBUG (MainThread) [custom_components.jq300] Finished fetching ***@hu****s.com devices list in 1.825 seconds
2020-07-16 00:47:02 DEBUG (SyncWorker_8) [custom_components.jq300] Updating sensors state for account ***@hu****s.com
2020-07-16 00:47:02 DEBUG (SyncWorker_8) [custom_components.jq300] Querying https://www.youpinyuntai.com:31447/device/list
2020-07-16 00:47:03 DEBUG (SyncWorker_8) [custom_components.jq300] _query ret 200
2020-07-16 00:47:03 DEBUG (SyncWorker_8) [custom_components.jq300] b'jsoncallback({"returnCode":"0000","returnMsg":"\xe6\x88\x90\xe5\x8a\x9f","timestamp":0,"deviceValueVos":[{"content":"2","dptId":1,"seq":1},{"content":null,"dptId":1,"seq":2},{"content":null,"dptId":1,"seq":3},{"content":"30","dptId":1,"seq":4},{"content":"55","dptId":1,"seq":5},{"content":"37","dptId":1,"seq":6},{"content":"0.085","dptId":1,"seq":7},{"content":"0.528","dptId":1,"seq":8},{"content":"1062","dptId":1,"seq":9},{"content":null,"dptId":1,"seq":10}],"deviceToken":"84E17B9117426E7BA417"})'
2020-07-16 00:47:05 DEBUG (MainThread) [custom_components.jq300] Finished fetching ***@hu****s.com device's sensors in 3.138 seconds
2020-07-16 00:47:23 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Setup binary sensors for account ***@hu****s.com
2020-07-16 00:47:23 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Initialize binary_sensor.jq_300_air_quality_alert
2020-07-16 00:47:26 DEBUG (MainThread) [custom_components.jq300.sensor] Setup sensors for account ***@hu****s.com
2020-07-16 00:47:26 DEBUG (MainThread) [custom_components.jq300.sensor] Initialize sensor.jq_300_internal_temperature
2020-07-16 00:47:26 DEBUG (MainThread) [custom_components.jq300.sensor] Initialize sensor.jq_300_humidity
2020-07-16 00:47:26 DEBUG (MainThread) [custom_components.jq300.sensor] Initialize sensor.jq_300_pm25
2020-07-16 00:47:26 DEBUG (MainThread) [custom_components.jq300.sensor] Initialize sensor.jq_300_hcho
2020-07-16 00:47:26 DEBUG (MainThread) [custom_components.jq300.sensor] Initialize sensor.jq_300_tvoc
2020-07-16 00:47:26 DEBUG (MainThread) [custom_components.jq300.sensor] Initialize sensor.jq_300_eco2
```

**Comment by Limych** [comment] 2020-07-15 21:55
#6

**Comment by Limych** [comment] 2020-07-15 22:01
```text
2020-07-16 01:00:17 DEBUG (SyncWorker_13) [custom_components.jq300] Querying https://www.youpinyuntai.com:31447/device/list
2020-07-16 01:00:17 DEBUG (SyncWorker_13) [custom_components.jq300] b'jsoncallback({"returnCode":"9960","returnMsg":"Request so fast\xef\xbc\x81","timestamp":0})'
2020-07-16 01:00:17 ERROR (SyncWorker_13) [custom_components.jq300] Sorry.. Something went wrong...
```

:(

**Comment by Limych** [comment] 2020-07-15 23:02
I sent a letter to the Chinese server administrator asking to agree on the conditions for normal cooperation. Let's see what they answer ...

**Comment by Limych** [comment] 2020-07-15 23:29
I still did not understand if that letter was sent.
The first attempt ended with the message that the mailbox does not exist.
Attempts to find workarounds ended in complete uncertainty ...

**Comment by tomaae** [comment] 2020-07-16 01:37
just slowing down requests could work.

**Comment by Limych** [comment] 2020-07-16 07:29
Right.  But at the same time I want to squeeze out the maximum data.

**Comment by tomaae** [comment] 2020-07-16 10:24
oh sure, what I mean is to add a limiter for like one remote request per 2 seconds.
Not sure what the limit is for them, but once implemented, it can be adjusted to find out.

You can do that using global lock and storing epoch for example.

**Comment by Limych** [comment] 2020-07-16 11:15
I already made a request limitation modification last night.  But I didn't have time to test it.  And now I'm at work ...

**Comment by tomaae** [comment] 2020-07-16 17:25
thats fine, there is no need to hurry with it. too bad you didnt commited it, I would test it.

**Comment by stuart-c** [comment] 2020-07-21 14:57
I'm not sure if it is the same issue, but things are currently failing with this error reply:

b'jsoncallback({"returnCode":"9960","returnMsg":"Request so fast\xef\xbc\x81","timestamp":0})'

It looks like it tries to login and then fetch the list of devices, but the requests are too close together and therefore it is rate limited. The error then causes the login to fail and start again, which then fails with the same error.

Did you manage to release the code change that slows down requests @Limych?

**Comment by Limych** [comment] 2020-07-21 18:55
@stuart-c, Yes, is the same issue, alas.

I've just published new version of code with conservative updation of sensors. But I'm not close this issue because this version is just temporary crutch -- not the problem fix.

**Comment by tomaae** [comment] 2020-07-21 22:21
excellent, I'm going to test it

**Comment by tomaae** [comment] 2020-07-22 01:03
that did not helped :(

**Comment by stuart-c** [comment] 2020-07-22 06:18
It seemed to help to some extent for me. The first device does seem to be getting some data, but other devices are not checked. There still seems to be instances of the "Request so fast" error - I think it isn't just about the delay between polls, but also between individual API calls.

**Comment by Limych** [comment] 2020-07-22 06:21
I know ... It remains only to increase the interval in search of the permitted.  But now there is an interval of 10 minutes, which is too much for me.  IMHO it's time to look towards flashing the device and avoiding using their cloud.

**Comment by stuart-c** [comment] 2020-07-22 06:27
What polling interval are you hoping for @Limych? Most of my existing sensors (light, temperature) update every 30-60 minutes, so this updating even every 15 would already be much faster.

**Comment by Limych** [comment] 2020-07-22 06:49
An acceptable interval for me is at least 5 minutes.  Perfect - 1 minute.  So it will be possible to implement some kind of automation depending on the data from the sensors.  Moreover, the sensor clearly updates the data at least once a minute.  This can be seen from its reaction to opening a window when the red indicator is on.

**Comment by Limych** [comment] 2020-07-23 05:06
Alas, this is a big war... My new IP is blocked, although there were very few calls to the cloud from it.

**Comment by nelbarn** [comment] 2020-09-24 00:05
Sorry for resurecting an old thread but the error messages that I've been receiving would appear to be similar to those above. 
 I can't work out what the problem is but I've not been able to get this integration to work for me.

> "2020-09-24 00:46:27 INFO (MainThread) [homeassistant.setup] Setting up jq300
> 2020-09-24 00:46:27 INFO (MainThread) [custom_components.jq300] Version dev
> 2020-09-24 00:46:27 INFO (MainThread) [custom_components.jq300] If you have ANY issues with this, please report them here: https://github.com/Limych/ha-jq300/issues
> 2020-09-24 00:46:27 DEBUG (MainThread) [custom_components.jq300] Connecting to account ne**********0@ho****l.com
> 2020-09-24 00:46:27 DEBUG (SyncWorker_7) [custom_components.jq300] Querying http://www.youpinyuntai.com:32086/ypyt-api/api/app/loginByEmail
> 2020-09-24 00:46:28 DEBUG (SyncWorker_7) [custom_components.jq300] _query ret 200
> 2020-09-24 00:46:28 DEBUG (SyncWorker_7) [custom_components.jq300] b'{"action":"loginByEmail","code":2000,"uid":31062548,"safeToken":"DD8B48EF0E25432B8CE21205605B7C00","expireAt":0,"systime":0}'
> 2020-09-24 00:46:28 DEBUG (SyncWorker_7) [custom_components.jq300] Updating devices list for account ne**********0@ho****l.com
> 2020-09-24 00:46:28 DEBUG (SyncWorker_7) [custom_components.jq300] Querying http://www.youpinyuntai.com:32086/ypyt-api/api/app/deviceManager
> 2020-09-24 00:46:28 DEBUG (SyncWorker_7) [custom_components.jq300] _query ret 200
> 2020-09-24 00:46:28 DEBUG (SyncWorker_7) [custom_components.jq300] b'{"action":"deviceManager","code":2000,"deviceInfoBodyList":[{"circleid":"57bc22e972f9d27416581187","pt_name":"Living Room Air Sensor","pt_model":"JQ_300","brandname":"\xe5\x93\x81\xe4\xbc\x98","logo":"mlLogo.png","onlinestat":2,"flag":1,"id":28559,"deviceid":19829,"devstatus":6,"deviceToken":"35635B35654583595765","status":1,"href":"/resource/page/hcho/indexPm25.html","pic":"20161026101634psgscf591477448194","weburl":"http://market.cmbchina.com/ccard/xyksq/xyksq.html?WT.srch=1&WT.mc_id=N3700BD1057Z074200BZ","updtime":"1477448195","repairstatus":null}]}'
> 2020-09-24 00:46:29 DEBUG (MainThread) [custom_components.jq300] Finished fetching ne**********0@ho****l.com devices list in 1.624 seconds
> 2020-09-24 00:46:29 DEBUG (SyncWorker_5) [custom_components.jq300] Updating sensors state for account ne**********0@ho****l.com
> 2020-09-24 00:46:46 ERROR (MainThread) [custom_components.jq300] Timeout fetching ne**********0@ho****l.com device's sensors
> 2020-09-24 00:46:46 DEBUG (MainThread) [custom_components.jq300] Finished fetching ne**********0@ho****l.com device's sensors in 17.132 seconds
> 2020-09-24 00:46:46 INFO (MainThread) [homeassistant.setup] Setup of domain jq300 took 18.8 seconds
> 2020-09-24 00:46:46 ERROR (MainThread) [homeassistant.setup] Setup failed for jq300: Integration failed to initialize.
> 2020-09-24 00:53:49 WARNING (Recorder) [homeassistant.components.recorder] Event is not JSON serializable: <Event platform_discovered[L]: service=load_platform.sensor, platform=iaquk, discovered=name=jq300, sensors=dict_keys(['iaq_index', 'iaq_level'])>"

**Comment by Limych** [comment] 2020-12-04 06:19
Please, try to use latest version of integration. I think, this problem is solved.

**Closed by Limych** 2020-12-04 06:19 UTC
Labels: bug
