### ISSUE TITLE
Error on HA core-2022.3.0 b1 core-2022.3.0b0      Pi 4

### ISSUE THREAD

**Issue by kdutton1964** [Limych/ha-jq300#86] opened 2022-02-24 22:30 UTC
Logger: homeassistant.util.package
Source: util/package.py:99 
First occurred: 4:25:21 PM (3 occurrences) 
Last logged: 4:25:36 PM

Unable to install package paho-mqtt==1.5.1: ERROR: Cannot install paho-mqtt==1.5.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

And

Logger: homeassistant.setup
Source: setup.py:155 
First occurred: 4:25:36 PM (1 occurrences) 
Last logged: 4:25:36 PM

Setup failed for jq300: Requirements for jq300 not found: ['paho-mqtt==1.5.1'].

This is after deleting and attempting reinstall to solve issue.
Cleared cache.

Thank you for your great code!

**Environment**

- Home Assistant Core release with the issue:
- This custom component release with the issue:
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv):

**Describe the bug**

**Configuration.yaml**
```yaml

Add your configs here if any.

```

**Steps to Reproduce**

**Expected behavior**

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by Limych** [comment] 2022-02-26 21:26
* Checked at Home Assistant 2022.3.0b0 — works fine.
* Checked at Home Assistant 2022.3.0b1 — works fine.
* Checked at Home Assistant 2022.3.0b3 — works fine.
* Checked at Home Assistant 2022.4.0.dev0 — works fine.

I'm sorry, I can't reproduce your bug.

**Comment by Thrasher2020** [comment] 2022-02-28 09:32
Hi,

I have the same issue with 3.0b4

`Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 09:20:56 (3 occurrences)
Last logged: 09:21:16

Unable to install package paho-mqtt==1.5.1: ERROR: Cannot install paho-mqtt==1.5.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`

**Comment by PhillipRt** [comment] 2022-03-02 12:46
@Limych
The manifest.json should say "paho-mqtt==1.**6**.1" 

> {
>   "domain": "jq300",
>   "name": "JQ-300/200/100 Indoor Air Quality Meter",
>   "version": "0.10.2",
>   "documentation": "https://github.com/Limych/ha-jq300",
>   "issue_tracker": "https://github.com/Limych/ha-jq300/issues",
>   "dependencies": [],
>   "config_flow": false,
>   "codeowners": [
>     "@Limych"
>   ],
>   "requirements": [
>     "paho-mqtt==1.**5**.1"
>   ],
>   "iot_class": "cloud_push"
> }

**Comment by McGiverGim** [comment] 2022-03-02 20:40
The final version 2022.3.0 shows the same error for me.

**Comment by McGiverGim** [comment] 2022-03-02 22:00
Tested the change suggested by @PhillipRt and seems to work...

**Comment by kdutton1964** [comment] 2022-03-02 23:49
Also worked for me! All looks great again… thanks.

**Comment by dheuts90** [comment] 2022-03-07 14:13
Strange.
When I change the 1.5.1 to 1.6.1 in manifest.json, it still doesn't work.
Error: Integration error: jq300 - Requirements for jq300 not found: ['paho-mqtt==1.5.1'].

**Comment by remyderuysscher** [comment] 2022-03-08 19:42
Same for me on 2022.3.3

**Comment by socekin** [comment] 2022-03-16 10:45
Same for me on 2022.3.5
Integration error: jq300 - Requirements for jq300 not found: ['paho-mqtt==1.5.1'].

**Comment by remyderuysscher** [comment] 2022-03-16 11:34
Resolved for me on HA 2022.3.4 which fixes paho-mqtt

**Comment by socekin** [comment] 2022-03-26 15:27
> 

the issue fixed by change the version 1.5.1 to 1.6.1 in the file “manifest.json”

{
  "domain": "jq300",
  "name": "JQ-300/200/100 Indoor Air Quality Meter",
  "version": "0.10.2",
  "documentation": "https://github.com/Limych/ha-jq300",
  "issue_tracker": "https://github.com/Limych/ha-jq300/issues",
  "dependencies": [],
  "config_flow": false,
  "codeowners": [
    "@Limych"
  ],
  "requirements": [
    **"paho-mqtt==1.6.1"**
  ],
  "iot_class": "cloud_push"
}

**Closed as completed** 2022-07-18 14:54 UTC
Labels: bug
